//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donar
    {
        public int DonorId { get; set; }
        public string DonorName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string MobileNo { get; set; }
        public string Organ { get; set; }
        public string City { get; set; }
    }
}
